import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Recursive } from "next/font/google";
import "./globals.css";

export const recursive = Recursive({
  weight: "300",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-preface",
});


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
